export const NOTE_BUTTON_PRESSED = 'NOTE_BUTTON_PRESSED';
export const SAVE_NOTE_BUTTON_PRESSED = 'SAVE_NOTE_BUTTON_PRESSED';
export const EDIT_NOTE_BUTTON_PRESSED = 'EDIT_NOTE_BUTTON_PRESSED';

export const LEXICON_UPDATED = 'LEXICON UPDATED';
export const UPDATE_LEXICON = 'UPDATE LEXICON';
export const LEXICON_LOADING = 'LOADING LEXICON FROM SERVER';
export const LEXICON_LOAD_SUCCESS = 'LEXICON LOADED SUCCESSFULLY';
export const LEXICON_LOAD_ERROR = 'LEXICON LOADED FAILED';

export const MOVE_BLOCKS_CURSOR = 'SET CURSOR IN MARKED TEXT TO NEW POSITION';

export const CHOICE_DONE = 'SELECTED ONE OF THE OPTIONS';
export const TASK_SET = 'SET STEP BY STEP TASK SOLVING PROCESS ';


