export const NOTE_BUTTON_PRESSED = 'NOTE_BUTTON_PRESSED';
export const SAVE_NOTE_BUTTON_PRESSED = 'SAVE_NOTE_BUTTON_PRESSED';
export const EDIT_NOTE_BUTTON_PRESSED = 'EDIT_NOTE_BUTTON_PRESSED';
export const LEXICON_UPDATED = 'LEXICON_UPDATED';
export const UPDATE_LEXICON = 'UPDATE_LEXICON';
